name: Build, Lint, Test Elm Package

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, Lint, Test
    steps:
      - name: init
        uses: ./.github/workflows/_init.yml

      - name: elm-review
        run: pnpm run lint

      - name: elm make
        run: pnpm run build

      - name: elm-test-rs
        run: pnpm run test
