name: Compile Elm Sources

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Elm
      uses: youcefs21/setup-elm@1.2.1
    
    - name: Run Elm Review
      run: elm-review

    - name: Build the project
      run: elm make
